services:
  backend:
    build: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db  # <-- tutaj volume

volumes:
  mongo-dev-data: